#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2016-present Team LibreELEC (https://libreelec.tv)


TOPDIR=$(pwd)
PKG_NAME="mali-400"
PKG_MALI_VERSION="r5p0"
PKG_MALI_RELEASE="hk4412.x11"
PKG_MALI_URI="http://builder.mdrjr.net/tools/u3"
PKG_MALI_URL="${PKG_MALI_URI}/4412_${PKG_MALI_VERSION}_x11.tar.xz"
PKG_MESA_VERSION="$(grep ^PKG_VERSION $TOPDIR/../../../../packages/graphics/mesa/package.mk | awk -F '=' '{print $2}' | sed 's/["]//g')"
PKG_MESA_URI="ftp://ftp.freedesktop.org/pub/mesa"
PKG_MESA_URL="${PKG_MESA_URI}/mesa-$PKG_MESA_VERSION.tar.xz"
PKG_VERSION="$PKG_MALI_VERSION.$PKG_MALI_RELEASE"

sources() {
  echo -n "Getting Sources ... "

  if [ ! -d "mesa-$PKG_MESA_VERSION" ]; then
    ( wget -O- $PKG_MESA_URL | tar -C $TOPDIR -Jxf - ) || exit 1
  fi

  if [ ! -d "mali-400-$PKG_VERSION" ]; then
    mkdir -p $TOPDIR/4412-$PKG_MALI_VERSION
    ( wget -O- $PKG_MALI_URL | tar -C $TOPDIR/4412-$PKG_MALI_VERSION -Jxf - ) || exit 1
  fi

  echo "DONE"
}

package() {
  cd $TOPDIR

  if [ -d $PKG_NAME-$PKG_VERSION ]; then
    echo -n "Cleaning Old Release ... "
    rm -rf $PKG_NAME-$PKG_VERSION
    echo "DONE"
  fi

  echo -n "Copying to Release ... "
  mkdir -p $PKG_NAME-$PKG_VERSION/usr/include
    cp -PR mesa-$PKG_MESA_VERSION/include/EGL $PKG_NAME-$PKG_VERSION/usr/include
    cp -PR mesa-$PKG_MESA_VERSION/include/GLES $PKG_NAME-$PKG_VERSION/usr/include
    cp -PR mesa-$PKG_MESA_VERSION/include/GLES2 $PKG_NAME-$PKG_VERSION/usr/include
    cp -PR mesa-$PKG_MESA_VERSION/include/KHR $PKG_NAME-$PKG_VERSION/usr/include
  mkdir -p $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig
  # use a generic mali-mesa.pc file for all sub libs
    echo 'prefix=/usr'                    >> $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/mali-mesa.pc
    echo 'exec_prefix=${prefix}'          >> $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/mali-mesa.pc
    echo 'libdir=${prefix}/lib'           >> $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/mali-mesa.pc
    echo 'includedir=${prefix}/include'   >> $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/mali-mesa.pc
    echo ''                               >> $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/mali-mesa.pc
    echo 'Name: Mali/Mesa PkgConfig'      >> $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/mali-mesa.pc
    echo 'Description: Mali/Mesa library' >> $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/mali-mesa.pc
    echo "Version: $PKG_MALI_VERSION"     >> $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/mali-mesa.pc
    echo 'Libs: -L${libdir} -lMali'       >> $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/mali-mesa.pc
    echo 'Libs.private: -lm -lpthread'    >> $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/mali-mesa.pc
    echo 'Cflags: -I${includedir}'        >> $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/mali-mesa.pc

    for PKGCONFIG in egl gles glesv2 ; do
      ln -sfn mali-mesa.pc $PKG_NAME-$PKG_VERSION/usr/lib/pkgconfig/$PKGCONFIG.pc
    done

  mkdir -p $PKG_NAME-$PKG_VERSION/usr/lib
    cp -PR 4412-$PKG_MALI_VERSION/*.so* $PKG_NAME-$PKG_VERSION/usr/lib/

  echo "DONE"

  echo -n "Compressing Source ... "
  tar cJf $PKG_NAME-$PKG_VERSION.tar.xz $PKG_NAME-$PKG_VERSION
  echo "DONE"

  echo -n "Final Cleanup ... "
  rm -rf $PKG_NAME-$PKG_VERSION 4412-$PKG_MALI_VERSION mesa-$PKG_MESA_VERSION
  echo "DONE"
}

sources
package
